### ISSUE TITLE
Cannot List Files "ValueRequiredException"

### ISSUE THREAD

**Issue by hauketoenjes** [thegrizzlylabs/sardine-android#23]
Hello,

i ran into a problem while showing data from a webdav Server. The Problem is related to the decoding of the xml. I get a "ValueRequiredException" where it says that "lockentry" is needed, but our server does not use locking at all. Because of that it logs "Not a valid DAV response".

Stacktrace: 

`Caused by: org.simpleframework.xml.core.ValueRequiredException: Unable to satisfy @org.simpleframework.xml.ElementList(data=false, empty=true, entry=, inline=true, name=, required=true, type=void) on field 'lockentry' private java.util.List com.thegrizzlylabs.sardineandroid.model.Supportedlock.lockentry for class com.thegrizzlylabs.sardineandroid.model.Supportedlock at line -1
        at org.simpleframework.xml.core.Composite.validate(Composite.java:644)
        at org.simpleframework.xml.core.Composite.readElements(Composite.java:449)
        at org.simpleframework.xml.core.Composite.access$400(Composite.java:59)
        at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383)
        at org.simpleframework.xml.core.Composite.read(Composite.java:201)
        at org.simpleframework.xml.core.Composite.read(Composite.java:148)
        at org.simpleframework.xml.core.Traverser.read(Traverser.java:92)
        at org.simpleframework.xml.core.Persister.read(Persister.java:625)
        at org.simpleframework.xml.core.Persister.read(Persister.java:606)
        at org.simpleframework.xml.core.Persister.read(Persister.java:584)
        at org.simpleframework.xml.core.Persister.read(Persister.java:480)
        at com.thegrizzlylabs.sardineandroid.util.EntityWithAnyElementConverter.read(EntityWithAnyElementConverter.java:60)
        at com.thegrizzlylabs.sardineandroid.util.EntityWithAnyElementConverter.read(EntityWithAnyElementConverter.java:17)
        at org.simpleframework.xml.convert.RegistryStrategy.read(RegistryStrategy.java:129)
        at org.simpleframework.xml.convert.RegistryStrategy.read(RegistryStrategy.java:108)
        at org.simpleframework.xml.core.Source.getOverride(Source.java:360)
        at org.simpleframework.xml.core.Factory.getConversion(Factory.java:207)
        at org.simpleframework.xml.core.Factory.getOverride(Factory.java:139)
        at org.simpleframework.xml.core.ObjectFactory.getInstance(ObjectFactory.java:63)
        at org.simpleframework.xml.core.Composite.read(Composite.java:139)
        at org.simpleframework.xml.core.Composite.readVariable(Composite.java:623)
        at org.simpleframework.xml.core.Composite.readInstance(Composite.java:573)
        at org.simpleframework.xml.core.Composite.readUnion(Composite.java:549)
        at org.simpleframework.xml.core.Composite.readElement(Composite.java:532)
        at org.simpleframework.xml.core.Composite.readElements(Composite.java:445)
        at org.simpleframework.xml.core.Composite.access$400(Composite.java:59)
        at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383)
        at org.simpleframework.xml.core.Composite.read(Composite.java:201)
W/System.err:     at org.simpleframework.xml.core.Composite.read(Composite.java:148)
        at org.simpleframework.xml.core.Traverser.read(Traverser.java:92)
        at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:190)
        at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:167)
        at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:124)
        at org.simpleframework.xml.core.Composite.readVariable(Composite.java:623)
        at org.simpleframework.xml.core.Composite.readInstance(Composite.java:573)
        at org.simpleframework.xml.core.Composite.readUnion(Composite.java:549)
        at org.simpleframework.xml.core.Composite.readElement(Composite.java:532)
        at org.simpleframework.xml.core.Composite.readElements(Composite.java:445)
        at org.simpleframework.xml.core.Composite.access$400(Composite.java:59)
        at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383)
        at org.simpleframework.xml.core.Composite.read(Composite.java:201)
        at org.simpleframework.xml.core.Composite.read(Composite.java:148)
        at org.simpleframework.xml.core.Traverser.read(Traverser.java:92)
        at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:190)
        at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:167)
        at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:124)
        at org.simpleframework.xml.core.Composite.readVariable(Composite.java:623)
        at org.simpleframework.xml.core.Composite.readInstance(Composite.java:573)
        at org.simpleframework.xml.core.Composite.readUnion(Composite.java:549)
        at org.simpleframework.xml.core.Composite.readElement(Composite.java:532)
        at org.simpleframework.xml.core.Composite.readElements(Composite.java:445)
        at org.simpleframework.xml.core.Composite.access$400(Composite.java:59)
        at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383)
        at org.simpleframework.xml.core.Composite.read(Composite.java:201)
        at org.simpleframework.xml.core.Composite.read(Composite.java:148)
        at org.simpleframework.xml.core.Traverser.read(Traverser.java:92)
        at org.simpleframework.xml.core.Persister.read(Persister.java:625)
        at org.simpleframework.xml.core.Persister.read(Persister.java:606)
        at org.simpleframework.xml.core.Persister.read(Persister.java:584)
        at org.simpleframework.xml.core.Persister.read(Persister.java:543)
        at org.simpleframework.xml.core.Persister.read(Persister.java:444)
        at com.thegrizzlylabs.sardineandroid.util.SardineUtil.unmarshal(SardineUtil.java:135)
    	... 10 more`

**Comment by guillaume-tgl** [comment]
Would you mind pasting the XML response (or the part of it that causes this error)?

**Comment by hauketoenjes** [comment]
This the XML i get with an empty body in the request:

`<?xml version="1.0" encoding="utf-8"?>
<D:multistatus
  xmlns:D="DAV:">
  <D:response>
    <D:href>/</D:href>
    <D:propstat>
      <D:prop>
        <D:isvirtual>true</D:isvirtual>
        <D:cancontainusercontent>false</D:cancontainusercontent>
        <D:sharecount>0</D:sharecount>
        <D:resourcetype>
          <D:collection />
        </D:resourcetype>
        <D:getlastmodified>Thu, 07 Mar 2019 08:10:34 GMT</D:getlastmodified>
        <D:creationdate>2019-03-07T08:10:34.590Z</D:creationdate>
        <D:getcontentlength>0</D:getcontentlength>
        <D:lockdiscovery />
        <D:supportedlock />
      </D:prop>
      <D:status>HTTP/1.1 200 OK</D:status>
    </D:propstat>
  </D:response>
  <D:response>
    <D:href>/Mein%20Benutzerordner/</D:href>
    <D:propstat>
      <D:prop>
        <D:isvirtual>true</D:isvirtual>
        <D:cancontainusercontent>true</D:cancontainusercontent>
        <D:sharecount>0</D:sharecount>
        <D:resourcetype>
          <D:collection />
        </D:resourcetype>
        <D:getlastmodified>Thu, 07 Mar 2019 08:10:34 GMT</D:getlastmodified>
        <D:creationdate>2019-03-07T08:10:34.591Z</D:creationdate>
        <D:getcontentlength>0</D:getcontentlength>
        <D:lockdiscovery />
        <D:supportedlock />
      </D:prop>
      <D:status>HTTP/1.1 200 OK</D:status>
    </D:propstat>
  </D:response>
  <D:response>
    <D:href>/%C3%96ffentliche%20Ordner/</D:href>
    <D:propstat>
      <D:prop>
        <D:isvirtual>true</D:isvirtual>
        <D:cancontainusercontent>false</D:cancontainusercontent>
        <D:sharecount>0</D:sharecount>
        <D:resourcetype>
          <D:collection />
        </D:resourcetype>
        <D:getlastmodified>Thu, 07 Mar 2019 08:10:34 GMT</D:getlastmodified>
        <D:creationdate>2019-03-07T08:10:34.591Z</D:creationdate>
        <D:getcontentlength>0</D:getcontentlength>
        <D:lockdiscovery />
        <D:supportedlock />
      </D:prop>
      <D:status>HTTP/1.1 200 OK</D:status>
    </D:propstat>
  </D:response>
  <D:response>
    <D:href>/Meine%20Kurse/</D:href>
    <D:propstat>
      <D:prop>
        <D:isvirtual>true</D:isvirtual>
        <D:cancontainusercontent>false</D:cancontainusercontent>
        <D:sharecount>0</D:sharecount>
        <D:resourcetype>
          <D:collection />
        </D:resourcetype>
        <D:getlastmodified>Thu, 07 Mar 2019 08:10:34 GMT</D:getlastmodified>
        <D:creationdate>2019-03-07T08:10:34.592Z</D:creationdate>
        <D:getcontentlength>0</D:getcontentlength>
        <D:lockdiscovery />
        <D:supportedlock />
      </D:prop>
      <D:status>HTTP/1.1 200 OK</D:status>
    </D:propstat>
  </D:response>
</D:multistatus>`

**Comment by guillaume-tgl** [comment]
Can you check this branch and let me know if it handles correctly your XML response? https://github.com/thegrizzlylabs/sardine-android/tree/empty_supportedlock

**Comment by hauketoenjes** [comment]
I just tested it and there were no Problems with that branch!

Thank you!

**Comment by guillaume-tgl** [comment]
Great, I will release a new version with this change.
