### ISSUE TITLE
Error contacting, when using sardine.put() to upload files

### ISSUE THREAD

**Issue by rtkCode** [thegrizzlylabs/sardine-android#38]
`I/System.out: Authenticating for response: Response{protocol=h2, code=401, message=, url=https://dav.jianguoyun.com/dav/Chatterboxxxx_backup/ChatterBoxxxx_backup_2020_02_07_10:45.csv}
I/System.out: Challenges: [Basic authParams={realm=nutstore}]
W/System.err: com.thegrizzlylabs.sardineandroid.impl.SardineException: Error contacting https://dav.jianguoyun.com/dav/Chatterboxxxx_backup/ChatterBoxxxx_backup_2020_02_07_10:45.csv (400 )
W/System.err:     at com.thegrizzlylabs.sardineandroid.impl.handler.ValidatingResponseHandler.validateResponse(ValidatingResponseHandler.java:23)
        at com.thegrizzlylabs.sardineandroid.impl.handler.VoidResponseHandler.handleResponse(VoidResponseHandler.java:21)
        at com.thegrizzlylabs.sardineandroid.impl.handler.VoidResponseHandler.handleResponse(VoidResponseHandler.java:17)
W/System.err:     at com.thegrizzlylabs.sardineandroid.impl.OkHttpSardine.execute(OkHttpSardine.java:595)
        at com.thegrizzlylabs.sardineandroid.impl.OkHttpSardine.execute(OkHttpSardine.java:590)
        at com.thegrizzlylabs.sardineandroid.impl.OkHttpSardine.put(OkHttpSardine.java:326)
        at com.thegrizzlylabs.sardineandroid.impl.OkHttpSardine.put(OkHttpSardine.java:317)
W/System.err:     at com.thegrizzlylabs.sardineandroid.impl.OkHttpSardine.put(OkHttpSardine.java:296)
        at com.thegrizzlylabs.sardineandroid.impl.OkHttpSardine.put(OkHttpSardine.java:289)
        at com.rtk.chatterboxxxx.CloudSync$1$1.run(CloudSync.java:91)
        at java.lang.Thread.run(Thread.java:764)`

**Comment by rtkCode** [comment]
I want to upload a file to a WebDAV server. However, the method put() only allows replacing an existed file.

**Comment by guillaume-tgl** [comment]
The error you pasted looks like an authentication issue. What do you expect when you use the `put` method with a filename that already exists?

**Comment by rtkCode** [comment]
I have fixed this problem. It seems that the server does not support some special characters. Thanks
