### ISSUE TITLE
android.os.NetworkOnMainThreadException when trying basic example

### ISSUE THREAD

**Issue by Crosswind** [thegrizzlylabs/sardine-android#5]
When trying your basic example from the README.md I'll get the following stackstrace:

`FATAL EXCEPTION: main
                                                              Process: hftl.beam_it, PID: 24346
                                                              java.lang.RuntimeException: Unable to start activity ComponentInfo{hftl.beam_it/hftl.beam_it.activities.Overview}: android.os.NetworkOnMainThreadException
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                                  at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                  at android.os.Looper.loop(Looper.java:164)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                               Caused by: android.os.NetworkOnMainThreadException
                                                                  at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1448)
                                                                  at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:102)
                                                                  at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90)
                                                                  at java.net.InetAddress.getAllByName(InetAddress.java:787)
                                                                  at okhttp3.Dns$1.lookup(Dns.java:40)
                                                                  at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
                                                                  at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
                                                                  at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
                                                                  at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:213)
                                                                  at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
                                                                  at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
                                                                  at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                                                                  at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                                                                  at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                                                                  at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                                                                  at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
                                                                  at okhttp3.RealCall.execute(RealCall.java:77)
                                                                  at com.thegrizzlylabs.sardineandroid.impl.OkHttpSardine.execute(OkHttpSardine.java:606)
                                                                  at com.thegrizzlylabs.sardineandroid.impl.OkHttpSardine.propfind(OkHttpSardine.java:157)
                                                                  at com.thegrizzlylabs.sardineandroid.impl.OkHttpSardine.list(OkHttpSardine.java:126)
                                                                  at com.thegrizzlylabs.sardineandroid.impl.OkHttpSardine.list(OkHttpSardine.java:102)
                                                                  at com.thegrizzlylabs.sardineandroid.impl.OkHttpSardine.list(OkHttpSardine.java:97)
                                                                  at hftl.beam_it.activities.Overview.onCreate(Overview.java:110)
                                                                  at android.app.Activity.performCreate(Activity.java:6975)
                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
                                                                  at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                  at android.os.Looper.loop(Looper.java:164) 
                                                                  at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                  at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) `

I did use your exact code but it seems like it's complaining that the networking is done on the Main Thread instead of using an Async Task. Can I fix this on my end?

Thanks.

**Comment by NLLAPPS** [comment]
I am not the owner of the repo but you need to shift Network operation to another thread

**Comment by Crosswind** [comment]
Yeah I probably was a second too fast opening this issue. Thanks.

**Comment by guillaume-tgl** [comment]
Exactly, call this in an `AsyncTask` for example.
