### ISSUE TITLE
Exception in Android R

### ISSUE THREAD

**Issue by scubajeff** [thegrizzlylabs/sardine-android#51]
OkHttpSardine() builder throw exception in Android R:

    Process: site.leos.apps.lespas, PID: 5568
    java.lang.ExceptionInInitializerError
        at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:219)
        at okhttp3.OkHttpClient$Builder.build(OkHttpClient.kt:955)
        at com.thegrizzlylabs.sardineandroid.impl.OkHttpSardine.<init>(OkHttpSardine.java:73)
        at site.leos.apps.lespas.sync.SyncAdapter.onPerformSync(SyncAdapter.kt:40)
        at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:334)
     Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 30
        at okhttp3.internal.platform.AndroidPlatform$Companion.buildIfSupported(AndroidPlatform.kt:370)
        at okhttp3.internal.platform.Platform$Companion.findPlatform(Platform.kt:204)
        at okhttp3.internal.platform.Platform$Companion.access$findPlatform(Platform.kt:178)
        at okhttp3.internal.platform.Platform.<clinit>(Platform.kt:179)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:219) 
        at okhttp3.OkHttpClient$Builder.build(OkHttpClient.kt:955) 
        at com.thegrizzlylabs.sardineandroid.impl.OkHttpSardine.<init>(OkHttpSardine.java:73) 
        at site.leos.apps.lespas.sync.SyncAdapter.onPerformSync(SyncAdapter.kt:40) 
        at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:334)

**Comment by scubajeff** [comment]
Never mind, it's a upstream OkHttp3 bug, manage to solve it by replacing transitive dependency of sardine to the latest OkHttp3
