### ISSUE TITLE
sardine.("")  Not a valid DAV response

### ISSUE THREAD

**Issue by AttemptD** [thegrizzlylabs/sardine-android#67]
I test createDirectory is ok,but when I use list yo get all files will be that ,i don't know why

2022-01-22 09:44:11.847 22086-22362/com.attempt.Ainfuse W/System.err: java.io.IOException: Not a valid DAV response
2022-01-22 09:44:11.847 22086-22362/com.attempt.Ainfuse W/System.err:     at com.thegrizzlylabs.sardineandroid.util.SardineUtil.unmarshal(SardineUtil.java:142)
2022-01-22 09:44:11.847 22086-22362/com.attempt.Ainfuse W/System.err:     at com.thegrizzlylabs.sardineandroid.impl.handler.MultiStatusResponseHandler.getMultistatus(MultiStatusResponseHandler.java:38)
2022-01-22 09:44:11.847 22086-22362/com.attempt.Ainfuse W/System.err:     at com.thegrizzlylabs.sardineandroid.impl.handler.MultiStatusResponseHandler.handleResponse(MultiStatusResponseHandler.java:27)
2022-01-22 09:44:11.847 22086-22362/com.attempt.Ainfuse W/System.err:     at com.thegrizzlylabs.sardineandroid.impl.handler.ResourcesResponseHandler.handleResponse(ResourcesResponseHandler.java:25)
2022-01-22 09:44:11.847 22086-22362/com.attempt.Ainfuse W/System.err:     at com.thegrizzlylabs.sardineandroid.impl.handler.ResourcesResponseHandler.handleResponse(ResourcesResponseHandler.java:19)
2022-01-22 09:44:11.847 22086-22362/com.attempt.Ainfuse W/System.err:     at com.thegrizzlylabs.sardineandroid.impl.OkHttpSardine.execute(OkHttpSardine.java:627)
2022-01-22 09:44:11.847 22086-22362/com.attempt.Ainfuse W/System.err:     at com.thegrizzlylabs.sardineandroid.impl.OkHttpSardine.propfind(OkHttpSardine.java:180)
2022-01-22 09:44:11.847 22086-22362/com.attempt.Ainfuse W/System.err:     at com.thegrizzlylabs.sardineandroid.impl.OkHttpSardine.list(OkHttpSardine.java:149)
2022-01-22 09:44:11.847 22086-22362/com.attempt.Ainfuse W/System.err:     at com.thegrizzlylabs.sardineandroid.impl.OkHttpSardine.list(OkHttpSardine.java:125)
2022-01-22 09:44:11.847 22086-22362/com.attempt.Ainfuse W/System.err:     at com.thegrizzlylabs.sardineandroid.impl.OkHttpSardine.list(OkHttpSardine.java:120)
2022-01-22 09:44:11.847 22086-22362/com.attempt.Ainfuse W/System.err:     at com.thegrizzlylabs.sardineandroid.impl.OkHttpSardine.getResources(OkHttpSardine.java:115)
2022-01-22 09:44:11.847 22086-22362/com.attempt.Ainfuse W/System.err:     at com.attempt.Ainfuse.View.fragments.FileChildView.Add_resources.lambda$initView$5(Add_resources.java:226)
2022-01-22 09:44:11.847 22086-22362/com.attempt.Ainfuse W/System.err:     at com.attempt.Ainfuse.View.fragments.FileChildView.Add_resources$$ExternalSyntheticLambda9.run(Unknown Source:0)
2022-01-22 09:44:11.847 22086-22362/com.attempt.Ainfuse W/System.err:     at java.lang.Thread.run(Thread.java:923)
2022-01-22 09:44:11.847 22086-22362/com.attempt.Ainfuse W/System.err: Caused by: org.simpleframework.xml.core.ElementException: Element 'write' does not have a match in class com.thegrizzlylabs.sardineandroid.model.Lockscope at line 1
2022-01-22 09:44:11.847 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.readElement(Composite.java:527)
2022-01-22 09:44:11.847 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.readElements(Composite.java:445)
2022-01-22 09:44:11.847 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.access$400(Composite.java:59)
2022-01-22 09:44:11.847 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.read(Composite.java:201)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.read(Composite.java:148)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.readVariable(Composite.java:623)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.readInstance(Composite.java:573)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.readUnion(Composite.java:549)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.readElement(Composite.java:532)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.readElements(Composite.java:445)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.access$400(Composite.java:59)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.read(Composite.java:201)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.read(Composite.java:148)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Traverser.read(Traverser.java:92)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:190)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:167)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:124)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.readVariable(Composite.java:623)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.readInstance(Composite.java:573)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.readUnion(Composite.java:549)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.readElement(Composite.java:532)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.readElements(Composite.java:445)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.access$400(Composite.java:59)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.read(Composite.java:201)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.read(Composite.java:148)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Traverser.read(Traverser.java:92)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Persister.read(Persister.java:625)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Persister.read(Persister.java:606)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Persister.read(Persister.java:584)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Persister.read(Persister.java:480)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at com.thegrizzlylabs.sardineandroid.util.EntityWithAnyElementConverter.read(EntityWithAnyElementConverter.java:60)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at com.thegrizzlylabs.sardineandroid.util.EntityWithAnyElementConverter.read(EntityWithAnyElementConverter.java:17)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.convert.RegistryStrategy.read(RegistryStrategy.java:129)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.convert.RegistryStrategy.read(RegistryStrategy.java:108)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Source.getOverride(Source.java:360)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Factory.getConversion(Factory.java:207)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Factory.getOverride(Factory.java:139)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.ObjectFactory.getInstance(ObjectFactory.java:63)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.read(Composite.java:139)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.readVariable(Composite.java:623)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.readInstance(Composite.java:573)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.readUnion(Composite.java:549)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.readElement(Composite.java:532)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.readElements(Composite.java:445)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.access$400(Composite.java:59)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.read(Composite.java:201)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.read(Composite.java:148)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Traverser.read(Traverser.java:92)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:190)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:167)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:124)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.readVariable(Composite.java:623)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.readInstance(Composite.java:573)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.readUnion(Composite.java:549)
2022-01-22 09:44:11.848 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.readElement(Composite.java:532)
2022-01-22 09:44:11.849 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.readElements(Composite.java:445)
2022-01-22 09:44:11.849 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.access$400(Composite.java:59)
2022-01-22 09:44:11.849 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383)
2022-01-22 09:44:11.849 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.read(Composite.java:201)
2022-01-22 09:44:11.849 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.read(Composite.java:148)
2022-01-22 09:44:11.849 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Traverser.read(Traverser.java:92)
2022-01-22 09:44:11.849 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:190)
2022-01-22 09:44:11.849 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:167)
2022-01-22 09:44:11.849 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:124)
2022-01-22 09:44:11.849 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.readVariable(Composite.java:623)
2022-01-22 09:44:11.849 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.readInstance(Composite.java:573)
2022-01-22 09:44:11.849 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.readUnion(Composite.java:549)
2022-01-22 09:44:11.849 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.readElement(Composite.java:532)
2022-01-22 09:44:11.849 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.readElements(Composite.java:445)
2022-01-22 09:44:11.849 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.access$400(Composite.java:59)
2022-01-22 09:44:11.849 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383)
2022-01-22 09:44:11.849 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.read(Composite.java:201)
2022-01-22 09:44:11.849 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Composite.read(Composite.java:148)
2022-01-22 09:44:11.849 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Traverser.read(Traverser.java:92)
2022-01-22 09:44:11.849 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Persister.read(Persister.java:625)
2022-01-22 09:44:11.849 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Persister.read(Persister.java:606)
2022-01-22 09:44:11.849 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Persister.read(Persister.java:584)
2022-01-22 09:44:11.849 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Persister.read(Persister.java:543)
2022-01-22 09:44:11.849 22086-22362/com.attempt.Ainfuse W/System.err:     at org.simpleframework.xml.core.Persister.read(Persister.java:444)
2022-01-22 09:44:11.849 22086-22362/com.attempt.Ainfuse W/System.err:     at com.thegrizzlylabs.sardineandroid.util.SardineUtil.unmarshal(SardineUtil.java:137)
2022-01-22 09:44:11.849 22086-22362/com.attempt.Ainfuse W/System.err: 	... 13 more

My proguard-rules.pro already have  -keep class com.thegrizzlylabs.sardineandroid.** {*;} 

following my request 

header:

Accept-Encoding: gzip
Authorization: Basic MTY2MDU2MzczMDA6ZG1qMjQ5OTE0NzI3MQ==
Connection: Keep-Alive
Content-Length: 96
Content-Type: text/xml; charset=utf-8
Depth: 1
Host: 192.168.6.1:8081
User-Agent: okhttp/4.9.3

body
<?xml version="1.0" encoding="utf-8"?>
<D:propfind xmlns:D="DAV:">
    <D:allprop />
</D:propfind>

response :

cache-control: no-cache
content-type: application/xml; charset=utf-8
date: Sat, 22 Jan 2022 01:48:49 GMT
pragma: no-cache
transfer-encoding: chunked

body(xml)
not availale

status code :207

**Comment by litianjun05090** [comment]
I have the same problem , after testing ,  I find that this library does not support listing root directory . If you change the url to like http://192.168.6.1:8081/subfolder  , it will work

**Comment by AttemptD** [comment]
If you want use webdav ,you can use okhttp to request your url.when you make your request be get,you can get Response ,it will be html, then you Analysis html get whole path
