### ISSUE TITLE
java.io.IOException: Not a valid DAV response

### ISSUE THREAD

**Issue by cxincx** [thegrizzlylabs/sardine-android#69]
2022-06-21 11:36:04.826 16423-16539/? W/System.err: java.io.IOException: Not a valid DAV response
2022-06-21 11:36:04.831 16423-16539/? W/System.err:     at com.thegrizzlylabs.sardineandroid.util.SardineUtil.unmarshal(SardineUtil.java:142)
2022-06-21 11:36:04.836 16423-16539/? W/System.err:     at com.thegrizzlylabs.sardineandroid.impl.handler.MultiStatusResponseHandler.getMultistatus(MultiStatusResponseHandler.java:38)
2022-06-21 11:36:04.839 16423-16539/? W/System.err:     at com.thegrizzlylabs.sardineandroid.impl.handler.MultiStatusResponseHandler.handleResponse(MultiStatusResponseHandler.java:27)
2022-06-21 11:36:04.840 16423-16539/? W/System.err:     at com.thegrizzlylabs.sardineandroid.impl.handler.ResourcesResponseHandler.handleResponse(ResourcesResponseHandler.java:25)
2022-06-21 11:36:04.841 16423-16539/? W/System.err:     at com.thegrizzlylabs.sardineandroid.impl.handler.ResourcesResponseHandler.handleResponse(ResourcesResponseHandler.java:19)
2022-06-21 11:36:04.842 16423-16539/? W/System.err:     at com.thegrizzlylabs.sardineandroid.impl.OkHttpSardine.execute(OkHttpSardine.java:627)
2022-06-21 11:36:04.842 16423-16539/? W/System.err:     at com.thegrizzlylabs.sardineandroid.impl.OkHttpSardine.propfind(OkHttpSardine.java:180)
2022-06-21 11:36:04.843 16423-16539/? W/System.err:     at com.thegrizzlylabs.sardineandroid.impl.OkHttpSardine.list(OkHttpSardine.java:149)
2022-06-21 11:36:04.844 16423-16539/? W/System.err:     at com.thegrizzlylabs.sardineandroid.impl.OkHttpSardine.list(OkHttpSardine.java:125)
2022-06-21 11:36:04.845 16423-16539/? W/System.err:     at com.thegrizzlylabs.sardineandroid.impl.OkHttpSardine.list(OkHttpSardine.java:120)
2022-06-21 11:36:04.846 16423-16539/? W/System.err:     at com.cxincx.xxjz.setting.backup.webdav.SyncManager.listAllFile(SyncManager.java:193)
2022-06-21 11:36:04.848 16423-16539/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2022-06-21 11:36:04.849 16423-16539/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2022-06-21 11:36:04.849 16423-16539/? W/System.err:     at java.lang.Thread.run(Thread.java:920)
2022-06-21 11:36:04.850 16423-16539/? W/System.err: Caused by: org.simpleframework.xml.core.ElementException: Element 'extendFileList' does not have a match in class com.thegrizzlylabs.sardineandroid.model.Multistatus at line -1
2022-06-21 11:36:04.850 16423-16539/? W/System.err:     at org.simpleframework.xml.core.Composite.readElement(Composite.java:527)
2022-06-21 11:36:04.851 16423-16539/? W/System.err:     at org.simpleframework.xml.core.Composite.readElements(Composite.java:445)
2022-06-21 11:36:04.851 16423-16539/? W/System.err:     at org.simpleframework.xml.core.Composite.access$400(Composite.java:59)
2022-06-21 11:36:04.851 16423-16539/? W/System.err:     at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383)
2022-06-21 11:36:04.851 16423-16539/? W/System.err:     at org.simpleframework.xml.core.Composite.read(Composite.java:201)
2022-06-21 11:36:04.852 16423-16539/? W/System.err:     at org.simpleframework.xml.core.Composite.read(Composite.java:148)
2022-06-21 11:36:04.852 16423-16539/? W/System.err:     at org.simpleframework.xml.core.Traverser.read(Traverser.java:92)
2022-06-21 11:36:04.852 16423-16539/? W/System.err:     at org.simpleframework.xml.core.Persister.read(Persister.java:625)
2022-06-21 11:36:04.852 16423-16539/? W/System.err:     at org.simpleframework.xml.core.Persister.read(Persister.java:606)
2022-06-21 11:36:04.853 16423-16539/? W/System.err:     at org.simpleframework.xml.core.Persister.read(Persister.java:584)
2022-06-21 11:36:04.853 16423-16539/? W/System.err:     at org.simpleframework.xml.core.Persister.read(Persister.java:543)
2022-06-21 11:36:04.853 16423-16539/? W/System.err:     at org.simpleframework.xml.core.Persister.read(Persister.java:444)
2022-06-21 11:36:04.853 16423-16539/? W/System.err:     at com.thegrizzlylabs.sardineandroid.util.SardineUtil.unmarshal(SardineUtil.java:137)
2022-06-21 11:36:04.854 16423-16539/? W/System.err: 	... 14 more

**Comment by kyriej** [comment]
the webdav server return not a valid format
