### ISSUE TITLE
Yandex Webdav 

### ISSUE THREAD

**Issue by NLLAPPS** [thegrizzlylabs/sardine-android#7]
Hi, I am trying to figure it out what causing the following issues.
If a file is larger then about 500 KB you get the following error on Yandex Webdav (https://disk.yandex.com) service. You can test your self too. Simply register a test account at yandex.com and use https://webdav.yandex.com with your username and password

This does not happen with other webdav clients. For example CarrotDav from http://rei.to/

`2018-08-23 22:03:04.991 28160-30453/com.sample W/System.err: javax.net.ssl.SSLException: Write error: ssl=0xc23ae620: I/O error during system call, Broken pipe
2018-08-23 22:03:04.999 28160-30453/com.sample W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_write(Native Method)
2018-08-23 22:03:04.999 28160-30453/com.sample W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:832)
2018-08-23 22:03:04.999 28160-30453/com.sample W/System.err:     at LHa.write(Okio.java:79)
2018-08-23 22:03:04.999 28160-30453/com.sample W/System.err:     at wHa.write(AsyncTimeout.java:180)
2018-08-23 22:03:05.000 28160-30453/com.sample W/System.err:     at PHa.h(RealBufferedSink.java:179)
2018-08-23 22:03:05.000 28160-30453/com.sample W/System.err:     at PHa.write(RealBufferedSink.java:42)
2018-08-23 22:03:05.000 28160-30453/com.sample W/System.err:     at MGa$d.write(Http1Codec.java:295)
2018-08-23 22:03:05.000 28160-30453/com.sample W/System.err:     at GHa.write(ForwardingSink.java:35)
2018-08-23 22:03:05.000 28160-30453/com.sample W/System.err:     at zGa$a.write(CallServerInterceptor.java:149)
2018-08-23 22:03:05.001 28160-30453/com.sample W/System.err:     at PHa.h(RealBufferedSink.java:179)
2018-08-23 22:03:05.001 28160-30453/com.sample W/System.err:     at PHa.a(RealBufferedSink.java:107)
2018-08-23 22:03:05.001 28160-30453/com.sample W/System.err:     at ZFa.writeTo(RequestBody.java:120)
2018-08-23 22:03:05.001 28160-30453/com.sample W/System.err:     at zGa.intercept(CallServerInterceptor.java:72)
2018-08-23 22:03:05.001 28160-30453/com.sample W/System.err:     at FGa.a(RealInterceptorChain.java:147)
2018-08-23 22:03:05.001 28160-30453/com.sample W/System.err:     at rGa.intercept(ConnectInterceptor.java:45)
2018-08-23 22:03:05.001 28160-30453/com.sample W/System.err:     at FGa.a(RealInterceptorChain.java:147)
2018-08-23 22:03:05.001 28160-30453/com.sample W/System.err:     at FGa.a(RealInterceptorChain.java:121)
2018-08-23 22:03:05.002 28160-30453/com.sample W/System.err:     at nGa.intercept(CacheInterceptor.java:93)
2018-08-23 22:03:05.002 28160-30453/com.sample W/System.err:     at FGa.a(RealInterceptorChain.java:147)
2018-08-23 22:03:05.002 28160-30453/com.sample W/System.err:     at FGa.a(RealInterceptorChain.java:121)
2018-08-23 22:03:05.002 28160-30453/com.sample W/System.err:     at yGa.intercept(BridgeInterceptor.java:93)
2018-08-23 22:03:05.002 28160-30453/com.sample W/System.err:     at FGa.a(RealInterceptorChain.java:147)
2018-08-23 22:03:05.003 28160-30453/com.sample W/System.err:     at IGa.intercept(RetryAndFollowUpInterceptor.java:126)
2018-08-23 22:03:05.003 28160-30453/com.sample W/System.err:     at FGa.a(RealInterceptorChain.java:147)
2018-08-23 22:03:05.003 28160-30453/com.sample W/System.err:     at FGa.a(RealInterceptorChain.java:121)
2018-08-23 22:03:05.003 28160-30453/com.sample W/System.err:     at VFa.d(RealCall.java:200)
2018-08-23 22:03:05.003 28160-30453/com.sample W/System.err:     at VFa.m(RealCall.java:77)
2018-08-23 22:03:05.004 28160-30453/com.sample W/System.err:     at uDa.a(OkHttpSardine.java:596)
2018-08-23 22:03:05.004 28160-30453/com.sample W/System.err:     at uDa.a(OkHttpSardine.java:592)
2018-08-23 22:03:05.004 28160-30453/com.sample W/System.err:     at uDa.a(OkHttpSardine.java:302)
2018-08-23 22:03:05.004 28160-30453/com.sample W/System.err:     at uDa.a(OkHttpSardine.java:289)
2018-08-23 22:03:05.005 28160-30453/com.sample W/System.err:     at uDa.a(OkHttpSardine.java:278)
2018-08-23 22:03:05.005 28160-30453/com.sample W/System.err:     at CBa.a(SardineWebDAV.java:101)`

**Comment by guillaume-tgl** [comment]
Thanks for reporting this issue. Could you tell me which device you use and which version of Android?

**Comment by NLLAPPS** [comment]
My teet device is note 8 with Android 8 but I have reports from all over the board.

It is definitely related to the size of the file.

**Comment by guillaume-tgl** [comment]
Ok, I think I found the issue. Yandex requires a preemptive athentication when uploading files over 300KB by WebDAV. I'll push a fix.

**Comment by NLLAPPS** [comment]
Thank you. 
I guess we will have to test each service to see if it requires it. Or, provide user a switch to enable disable it.
