### ISSUE TITLE
Connecting to carddav radicale server

### ISSUE THREAD

**Issue by piersonleo** [thegrizzlylabs/sardine-android#9]
Hello, I am aware that the library is for webdav but just to be sure, is it possible to use it to connect to carddav server?

Thank you.

**Comment by guillaume-tgl** [comment]
I've have no idea, I'm not really familiar with CardDAV but feel free to try it and let me know if you have any issue and I can have a look at it.

**Comment by piersonleo** [comment]
Thank you for the kind reply.

After trying it out for a bit using this snippet code

```
            Sardine sardine = new OkHttpSardine();
            sardine.setCredentials(username, password);

            try {
                List<DavResource> resources = sardine.list(url);
                Log.d("testcarddav", resources.toString());
            } catch (IOException e) {
                e.printStackTrace();
            }
```

I've encountered this issue:

Challenges [realm:  radicale - "password required" charset="java.nio.charset.charseticu[iso-8859-1]"]

```
   at com.thegrizzlylabs.sardineandroid.util.SardineUtil.unmarshal(SardineUtil.java:140)
        at com.thegrizzlylabs.sardineandroid.impl.handler.MultiStatusResponseHandler.getMultistatus(MultiStatusResponseHandler.java:38)
        at com.thegrizzlylabs.sardineandroid.impl.handler.MultiStatusResponseHandler.handleResponse(MultiStatusResponseHandler.java:27)
        at com.thegrizzlylabs.sardineandroid.impl.handler.ResourcesResponseHandler.handleResponse(ResourcesResponseHandler.java:25)
        at com.thegrizzlylabs.sardineandroid.impl.handler.ResourcesResponseHandler.handleResponse(ResourcesResponseHandler.java:19)
        at com.thegrizzlylabs.sardineandroid.impl.OkHttpSardine.execute(OkHttpSardine.java:595)
        at com.thegrizzlylabs.sardineandroid.impl.OkHttpSardine.propfind(OkHttpSardine.java:180)
        at com.thegrizzlylabs.sardineandroid.impl.OkHttpSardine.list(OkHttpSardine.java:149)
        at com.thegrizzlylabs.sardineandroid.impl.OkHttpSardine.list(OkHttpSardine.java:125)
        at com.thegrizzlylabs.sardineandroid.impl.OkHttpSardine.list(OkHttpSardine.java:120)
        at com.example.pierson.testcarddav.MainActivity$TestCardDav.doInBackground(MainActivity.java:37)
        at com.example.pierson.testcarddav.MainActivity$TestCardDav.doInBackground(MainActivity.java:28)
        at android.os.AsyncTask$2.call(AsyncTask.java:288)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
    Caused by: org.simpleframework.xml.core.ElementException: Element 'href' does not have a match in class com.thegrizzlylabs.sardineandroid.model.PrincipalCollectionSet at line 2
09-03 17:55:43.859 20914-20937/com.example.pierson.testcarddav W/System.err:     at org.simpleframework.xml.core.Composite.readElement(Composite.java:527)
        at org.simpleframework.xml.core.Composite.readElements(Composite.java:445)
        at org.simpleframework.xml.core.Composite.access$400(Composite.java:59)
        at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383)
        at org.simpleframework.xml.core.Composite.read(Composite.java:201)
        at org.simpleframework.xml.core.Composite.read(Composite.java:148)
        at org.simpleframework.xml.core.Traverser.read(Traverser.java:92)
09-03 17:55:43.864 20914-20937/com.example.pierson.testcarddav W/System.err:     at org.simpleframework.xml.core.Persister.read(Persister.java:625)
        at org.simpleframework.xml.core.Persister.read(Persister.java:606)
        at org.simpleframework.xml.core.Persister.read(Persister.java:584)
        at org.simpleframework.xml.core.Persister.read(Persister.java:480)
        at com.thegrizzlylabs.sardineandroid.model.Prop$PropConverter.read(Prop.java:335)
        at com.thegrizzlylabs.sardineandroid.model.Prop$PropConverter.read(Prop.java:306)
        at org.simpleframework.xml.convert.RegistryStrategy.read(RegistryStrategy.java:129)
        at org.simpleframework.xml.convert.RegistryStrategy.read(RegistryStrategy.java:108)
        at org.simpleframework.xml.core.Source.getOverride(Source.java:360)
        at org.simpleframework.xml.core.Factory.getConversion(Factory.java:207)
        at org.simpleframework.xml.core.Factory.getOverride(Factory.java:139)
        at org.simpleframework.xml.core.ObjectFactory.getInstance(ObjectFactory.java:63)
        at org.simpleframework.xml.core.Composite.read(Composite.java:139)
        at org.simpleframework.xml.core.Composite.readVariable(Composite.java:623)
        at org.simpleframework.xml.core.Composite.readInstance(Composite.java:573)
        at org.simpleframework.xml.core.Composite.readUnion(Composite.java:549)
        at org.simpleframework.xml.core.Composite.readElement(Composite.java:532)
09-03 17:55:43.869 20914-20937/com.example.pierson.testcarddav W/System.err:     at org.simpleframework.xml.core.Composite.readElements(Composite.java:445)
        at org.simpleframework.xml.core.Composite.access$400(Composite.java:59)
        at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383)
        at org.simpleframework.xml.core.Composite.read(Composite.java:201)
        at org.simpleframework.xml.core.Composite.read(Composite.java:148)
        at org.simpleframework.xml.core.Traverser.read(Traverser.java:92)
        at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:190)
        at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:167)
        at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:124)
        at org.simpleframework.xml.core.Composite.readVariable(Composite.java:623)
        at org.simpleframework.xml.core.Composite.readInstance(Composite.java:573)
09-03 17:55:43.874 20914-20937/com.example.pierson.testcarddav W/System.err:     at org.simpleframework.xml.core.Composite.readUnion(Composite.java:549)
        at org.simpleframework.xml.core.Composite.readElement(Composite.java:532)
        at org.simpleframework.xml.core.Composite.readElements(Composite.java:445)
        at org.simpleframework.xml.core.Composite.access$400(Composite.java:59)
        at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383)
        at org.simpleframework.xml.core.Composite.read(Composite.java:201)
        at org.simpleframework.xml.core.Composite.read(Composite.java:148)
        at org.simpleframework.xml.core.Traverser.read(Traverser.java:92)
09-03 17:55:43.874 20914-20937/com.example.pierson.testcarddav W/System.err:     at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:190)
        at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:167)
        at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:124)
        at org.simpleframework.xml.core.Composite.readVariable(Composite.java:623)
        at org.simpleframework.xml.core.Composite.readInstance(Composite.java:573)
09-03 17:55:43.879 20914-20937/com.example.pierson.testcarddav W/System.err:     at org.simpleframework.xml.core.Composite.readUnion(Composite.java:549)
        at org.simpleframework.xml.core.Composite.readElement(Composite.java:532)
        at org.simpleframework.xml.core.Composite.readElements(Composite.java:445)
        at org.simpleframework.xml.core.Composite.access$400(Composite.java:59)
        at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383)
        at org.simpleframework.xml.core.Composite.read(Composite.java:201)
        at org.simpleframework.xml.core.Composite.read(Composite.java:148)
        at org.simpleframework.xml.core.Traverser.read(Traverser.java:92)
        at org.simpleframework.xml.core.Persister.read(Persister.java:625)
        at org.simpleframework.xml.core.Persister.read(Persister.java:606)
        at org.simpleframework.xml.core.Persister.read(Persister.java:584)
        at org.simpleframework.xml.core.Persister.read(Persister.java:543)
        at org.simpleframework.xml.core.Persister.read(Persister.java:444)
        at com.thegrizzlylabs.sardineandroid.util.SardineUtil.unmarshal(SardineUtil.java:135)
    	... 17 more
```

I'm guessing it's something to do with the password?

**Comment by guillaume-tgl** [comment]
Could you either:
- give me the full configuration to reproduce (if you don't have sensitive passwords)
- or set a break point in `MultiStatusResponseHandler` after `body` is defined and tell me the value of `body.string()` when you run the same code?

**Comment by guillaume-tgl** [comment]
Thanks! I've improved the library to support more WebDAV features. Could you checkout the branch https://github.com/thegrizzlylabs/sardine-android/tree/improve_prop_support and let me know if this works better?

**Comment by piersonleo** [comment]
Awesome, it connects properly now, though there's one thing I noticed.

When I connect to a vcf (or non vcf) url like for example "https://dav.com/username/a/"

The resource list is shown as `[/username1/a/,  /username/a/...vcf, /username/a/...vcf,/username/a/...vcf, ...`

Is the first item "/username/a/"  supposed to be listed alongside the resources? Just want to make sure.

**Comment by guillaume-tgl** [comment]
Yes, to my knowledge, that's how webDAV works: when you request a list of resources, you specify the depth you'd like:
- for depth 0, you only get details about the resource you asked for
- for depth 1, you get the resource you asked for and its children
- for depth 2, you get the resource you asked for, its children and grand-children...

But we could have a separate method `listChildren` that would only return the first level children.
